### ISSUE TITLE
The "classifiers" imported in Main.py does not exist.

### ISSUE THREAD

**Issue by la-la-la-1** [Navidfoumani/Disjoint-CNN#1]
Hello, can you provide Disjoint-CNN network source code? The "classifiers" you mentioned in Main.py "from classifiers import DCNN_2L" does not exist and cannot run code.

**Comment by Navidfoumani** [comment]
Thank you for raising this issue. I apologize for the confusion caused by the missing "classifiers" in the Main.py file. We have addressed this issue by adding the classifiers to the repository. You can now find the Disjoint-CNN network source code, along with other models such as FCN, ResNet, and MC-CNN, for multivariate time series classification.

Please feel free to explore the repository and let us know if you have any further questions or need assistance.
